---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-dep
  labels:
    type: db
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 4
  template:
    metadata:
      name: mydb-pod
      labels:
        type: db
        app: mysql
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: paswd
...

