apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ng-dep
  labels:
    app: proxy
spec: 
  replicas: 2
  selector: 
   matchLabels: 
    app: revpo
  template: 
    metadata: 
      name: ng-pod
      labels:
        app: revpo 
    spec: 
      containers: 
        - name: mynginx
          image: nginx
          ports: 
           - containerPort: 80
             hostPort: 8080

